name: Deploy to GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - dev
    paths:
      - 'README.md'
      - '.github/assets/**'
      - '.github/workflows/page.yml'

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Jekyll config
        run: |
          cat > _config.yml << 'EOF'
          theme: jekyll-theme-cayman
          show_downloads: true
          EOF
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: weread.gh.yycc.dev
          publish_branch: gh-pages
          enable_jekyll: true
          keep_files: false
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
